version: "3.8"
volumes:
    gif-db: {}
services:
    app:
        image: aniramadoss2002/gif-collection:latest
        ports:
            - 3000:3000
        deploy:
            replicas: 3
            placement:
                constraints:
                    - "node.role==worker"
            update_config:
                delay: 10s
        environment:
            MONGO_CONFIG_FILE: /run/secrets/config.json
        secrets:
            - config.json
        networks:
            - default
            - monitoring
    mongo:
        image: mongo:5.0
        volumes:
            - gif-db:/data/db
        deploy:
            placement:
                constraints:
                    - "node.role==worker"
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
        deploy:
            placement:
                constraints:
                    - "node.role==worker"
networks:
    monitoring:
        external: true
secrets:
    config.json:
        external: true