version: "3.8"
volumes:
    gif-db: {}
services:
    app:
        image: aniramadoss2002/gif-collection:latest
        ports:
            - 3000:3000
    mongo:
        image: mongo:5.0
        volumes:
            - gif-db:/data/db
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
