services:
  proxy:
    image: traefik:2.4
    command: --providers.docker --api.insecure
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    name: proxy